name: Sync to Gitee
on: [push]  # Triggers on every push to GitHub

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Mirror to Gitee
        run: |
          git config --global user.name "幸福-SHKIBSADMAN"
          git config --global user.email "15917537+happiness---hkibsadman@user.noreply.gitee.com"
          git remote add gitee https://gitee.com/${{ secrets.GITEE_USER }}/${{ github.event.repository.name }}.git
          git push gitee HEAD:main --force
        env:
          GITEE_USER: happiness---hkibsadman 
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}    